/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedContextsRouteImport } from './routes/_authenticated/contexts'
import { Route as AuthenticatedClipsIndexRouteImport } from './routes/_authenticated/clips/index'
import { Route as AuthenticatedGtdIndexRouteImport } from './routes/_authenticated/gtd/index'
import { Route as AuthenticatedGtdProjectidRouteImport } from './routes/_authenticated/gtd/$projectid'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContextsRoute = AuthenticatedContextsRouteImport.update({
  id: '/contexts',
  path: '/contexts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClipsIndexRoute = AuthenticatedClipsIndexRouteImport.update({
  id: '/clips/',
  path: '/clips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGtdIndexRoute = AuthenticatedGtdIndexRouteImport.update({
  id: '/gtd/',
  path: '/gtd/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGtdProjectidRoute =
  AuthenticatedGtdProjectidRouteImport.update({
    id: '/gtd/$projectid',
    path: '/gtd/$projectid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/contexts': typeof AuthenticatedContextsRoute
  '/gtd/$projectid': typeof AuthenticatedGtdProjectidRoute
  '/clips/': typeof AuthenticatedClipsIndexRoute
  '/gtd/': typeof AuthenticatedGtdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contexts': typeof AuthenticatedContextsRoute
  '/': typeof AuthenticatedIndexRoute
  '/gtd/$projectid': typeof AuthenticatedGtdProjectidRoute
  '/clips': typeof AuthenticatedClipsIndexRoute
  '/gtd': typeof AuthenticatedGtdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/contexts': typeof AuthenticatedContextsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/gtd/$projectid': typeof AuthenticatedGtdProjectidRoute
  '/_authenticated/clips/': typeof AuthenticatedClipsIndexRoute
  '/_authenticated/gtd/': typeof AuthenticatedGtdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/login' | '/contexts' | '/gtd/$projectid' | '/clips/' | '/gtd/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/contexts' | '/' | '/gtd/$projectid' | '/clips' | '/gtd'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/contexts'
    | '/_authenticated/'
    | '/_authenticated/gtd/$projectid'
    | '/_authenticated/clips/'
    | '/_authenticated/gtd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contexts': {
      id: '/_authenticated/contexts'
      path: '/contexts'
      fullPath: '/contexts'
      preLoaderRoute: typeof AuthenticatedContextsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clips/': {
      id: '/_authenticated/clips/'
      path: '/clips'
      fullPath: '/clips/'
      preLoaderRoute: typeof AuthenticatedClipsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gtd/': {
      id: '/_authenticated/gtd/'
      path: '/gtd'
      fullPath: '/gtd/'
      preLoaderRoute: typeof AuthenticatedGtdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gtd/$projectid': {
      id: '/_authenticated/gtd/$projectid'
      path: '/gtd/$projectid'
      fullPath: '/gtd/$projectid'
      preLoaderRoute: typeof AuthenticatedGtdProjectidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContextsRoute: typeof AuthenticatedContextsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedGtdProjectidRoute: typeof AuthenticatedGtdProjectidRoute
  AuthenticatedClipsIndexRoute: typeof AuthenticatedClipsIndexRoute
  AuthenticatedGtdIndexRoute: typeof AuthenticatedGtdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContextsRoute: AuthenticatedContextsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedGtdProjectidRoute: AuthenticatedGtdProjectidRoute,
  AuthenticatedClipsIndexRoute: AuthenticatedClipsIndexRoute,
  AuthenticatedGtdIndexRoute: AuthenticatedGtdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
